services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html:delegated
      - /var/www/html/vendor
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8
    platform: linux/arm64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - dbdata:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d:ro

volumes:
  dbdata:
